#!/usr/bin/env python3
"""Load the star schema (owner: Person 4, Warehouse Modeller).

Order matters and is enforced by the code path below:

    1. dim_airport   (from OLTP reference data, ambiguous codes excluded)
    2. dim_airline   (from OLTP reference data)
    3. dim_time      (all 1 440 minutes, generated in-database)
    4. dim_date      (every service date present in the cleaned data)
    5. fact_flight   (only after every dimension key exists)

The fact load is a full refresh of the batch's dates: dimension rows are
upserted, then the fact rows for the affected dates are deleted and
re-inserted. That makes `make load` safe to run repeatedly.

Run:  make load
"""

from __future__ import annotations

import logging

import pandas as pd
from sqlalchemy import text

import config
from elt.transform.main import build_clean_dataframe
from elt.transform.validation import VALID_AIRPORTS

LOG = logging.getLogger("load")


# --------------------------------------------------------------------------
# 1. dim_airport - the role-playing dimension, loaded ONCE
# --------------------------------------------------------------------------
def load_dim_airport() -> int:
    """Upsert airports from the OLTP, excluding ambiguous metro codes.

    Only codes in VALID_AIRPORTS reach the warehouse, so every
    departure_airport_key and arrival_airport_key resolves to exactly one
    physical airport.
    """
    with config.oltp_engine().connect() as conn:
        airports = pd.read_sql(
            text(
                """
                SELECT code AS airport_code, name AS airport_name,
                       city, state, country
                FROM airport
                WHERE NOT is_ambiguous
                  AND code = ANY(:valid)
                ORDER BY code
                """
            ),
            conn,
            params={"valid": VALID_AIRPORTS},
        )

    with config.dw_engine().begin() as conn:
        for row in airports.to_dict("records"):
            conn.execute(
                text(
                    """
                    INSERT INTO dim_airport
                        (airport_code, airport_name, city, state, country)
                    VALUES (:airport_code, :airport_name, :city, :state, :country)
                    ON CONFLICT (airport_code) DO UPDATE SET
                        airport_name = EXCLUDED.airport_name,
                        city         = EXCLUDED.city,
                        state        = EXCLUDED.state,
                        country      = EXCLUDED.country,
                        updated_at   = now()
                    """
                ),
                row,
            )
    LOG.info("dim_airport: %d row(s) upserted", len(airports))
    return len(airports)


# --------------------------------------------------------------------------
# 2. dim_airline
# --------------------------------------------------------------------------
def load_dim_airline() -> int:
    with config.oltp_engine().connect() as conn:
        airlines = pd.read_sql(
            text(
                """
                SELECT iata_code AS airline_code, icao_code,
                       name AS airline_name, country
                FROM airline
                ORDER BY iata_code
                """
            ),
            conn,
        )

    with config.dw_engine().begin() as conn:
        for row in airlines.to_dict("records"):
            conn.execute(
                text(
                    """
                    INSERT INTO dim_airline
                        (airline_code, icao_code, airline_name, country)
                    VALUES (:airline_code, :icao_code, :airline_name, :country)
                    ON CONFLICT (airline_code) DO UPDATE SET
                        icao_code    = EXCLUDED.icao_code,
                        airline_name = EXCLUDED.airline_name,
                        country      = EXCLUDED.country,
                        updated_at   = now()
                    """
                ),
                row,
            )
    LOG.info("dim_airline: %d row(s) upserted", len(airlines))
    return len(airlines)


# --------------------------------------------------------------------------
# 3. dim_time - all 1 440 minutes, generated by the database
# --------------------------------------------------------------------------
DIM_TIME_SQL = """
INSERT INTO dim_time
    (time_key, hour_24, minute, am_pm, hour_12, time_24h, time_12h, day_part)
SELECT h * 100 + m                                   AS time_key,
       h                                             AS hour_24,
       m                                             AS minute,
       CASE WHEN h < 12 THEN 'AM' ELSE 'PM' END      AS am_pm,
       CASE WHEN h % 12 = 0 THEN 12 ELSE h % 12 END  AS hour_12,
       lpad(h::text, 2, '0') || ':' || lpad(m::text, 2, '0') AS time_24h,
       (CASE WHEN h % 12 = 0 THEN 12 ELSE h % 12 END)::text
           || ':' || lpad(m::text, 2, '0')
           || ' ' || CASE WHEN h < 12 THEN 'AM' ELSE 'PM' END AS time_12h,
       CASE
           WHEN h < 6  THEN 'Night'
           WHEN h < 12 THEN 'Morning'
           WHEN h < 18 THEN 'Afternoon'
           ELSE 'Evening'
       END                                           AS day_part
FROM generate_series(0, 23) AS h,
     generate_series(0, 59) AS m
ON CONFLICT (time_key) DO NOTHING
"""


def load_dim_time() -> int:
    with config.dw_engine().begin() as conn:
        conn.execute(text(DIM_TIME_SQL))
        total = conn.execute(text("SELECT count(*) FROM dim_time")).scalar_one()
    LOG.info("dim_time: %d row(s) present", total)
    assert total == 1440, f"dim_time must hold every minute of the day, got {total}"
    return total


# --------------------------------------------------------------------------
# 4. dim_date - only the dates the batch actually needs
# --------------------------------------------------------------------------
def load_dim_date(clean: pd.DataFrame) -> int:
    """Upsert one dim_date row per distinct service date in the batch.

    ponytail: dates are generated on demand rather than pre-filling a decade.
    Swap in a generate_series() range if the BI layer needs future dates for
    period-over-period comparisons.
    """
    dates = sorted({pd.Timestamp(d).date() for d in clean["service_date"]})
    rows = []
    for d in dates:
        stamp = pd.Timestamp(d)
        rows.append(
            {
                "date_key": int(stamp.strftime("%Y%m%d")),
                "full_date": d,
                "day": d.day,
                "month": d.month,
                "quarter": (d.month - 1) // 3 + 1,
                "year": d.year,
                "day_name": stamp.strftime("%A"),
                "month_name": stamp.strftime("%B"),
                "day_of_week": d.isoweekday(),          # 1 = Monday
                "is_weekend": d.isoweekday() >= 6,
            }
        )

    with config.dw_engine().begin() as conn:
        conn.execute(
            text(
                """
                INSERT INTO dim_date
                    (date_key, full_date, day, month, quarter, year,
                     day_name, month_name, day_of_week, is_weekend)
                VALUES (:date_key, :full_date, :day, :month, :quarter, :year,
                        :day_name, :month_name, :day_of_week, :is_weekend)
                ON CONFLICT (date_key) DO NOTHING
                """
            ),
            rows,
        )
    LOG.info("dim_date: %d date(s) ensured (%s .. %s)", len(rows), dates[0], dates[-1])
    return len(rows)


# --------------------------------------------------------------------------
# 5. fact_flight - last, once every key exists
# --------------------------------------------------------------------------
def _key_maps() -> tuple[dict[str, int], dict[str, int]]:
    """Natural key -> surrogate key lookups for the two dimensions the fact
    resolves in Python."""
    with config.dw_engine().connect() as conn:
        airports = dict(
            conn.execute(text("SELECT airport_code, airport_key FROM dim_airport")).all()
        )
        airlines = dict(
            conn.execute(text("SELECT airline_code, airline_key FROM dim_airline")).all()
        )
    return airports, airlines


def load_fact_flight(clean: pd.DataFrame) -> int:
    airport_keys, airline_keys = _key_maps()

    fact = pd.DataFrame(
        {
            "date_key": clean["date_key"].astype(int),
            "departure_time_key": clean["departure_time_key"].astype(int),
            "arrival_time_key": clean["arrival_time_key"].astype(int),
            # The SAME dimension resolved twice - the role-playing join.
            "departure_airport_key": clean["dep_code"].map(airport_keys),
            "arrival_airport_key": clean["arr_code"].map(airport_keys),
            "airline_key": clean["airline_code"].map(airline_keys),
            "flight_no": clean["flight_no"],
            "duration_minutes": clean["duration_minutes"].astype(int),
            "reported_duration_minutes": clean["reported_duration_minutes"],
            "crossed_midnight": clean["crossed_midnight"].astype(bool),
            "source_row_id": clean["source_row_id"],
        }
    )

    # A missing surrogate key means a dimension load was skipped or a code
    # slipped past validation. Fail the load rather than insert an orphan.
    unmapped = fact[
        fact[["departure_airport_key", "arrival_airport_key", "airline_key"]].isna().any(axis=1)
    ]
    if not unmapped.empty:
        raise RuntimeError(
            "cannot resolve dimension keys for:\n"
            + unmapped[["flight_no", "date_key"]].to_string(index=False)
        )

    for column in ("departure_airport_key", "arrival_airport_key", "airline_key"):
        fact[column] = fact[column].astype(int)

    date_keys = sorted(fact["date_key"].unique().tolist())
    with config.dw_engine().begin() as conn:
        # Idempotent reload of the affected dates only.
        conn.execute(
            text("DELETE FROM fact_flight WHERE date_key = ANY(:keys)"),
            {"keys": date_keys},
        )
        fact.to_sql("fact_flight", conn, if_exists="append", index=False, method="multi")
        total = conn.execute(text("SELECT count(*) FROM fact_flight")).scalar_one()

    LOG.info("fact_flight: %d row(s) inserted, %d total", len(fact), total)
    return len(fact)


# --------------------------------------------------------------------------
# Orchestration
# --------------------------------------------------------------------------
def load(clean: pd.DataFrame | None = None) -> dict[str, int]:
    """Dimensions first, then the fact. Returns per-table row counts."""
    if clean is None:
        clean, _rejects = build_clean_dataframe()
    if clean.empty:
        raise RuntimeError("no clean rows to load - check `make transform` output")

    counts = {
        "dim_airport": load_dim_airport(),
        "dim_airline": load_dim_airline(),
        "dim_time": load_dim_time(),
        "dim_date": load_dim_date(clean),
    }
    counts["fact_flight"] = load_fact_flight(clean)
    return counts


def main() -> int:
    config.configure_logging()
    counts = load()
    LOG.info("warehouse load complete: %s", counts)

    # Show the loaded star through the enriched view as a sanity check.
    with config.dw_engine().connect() as conn:
        preview = pd.read_sql(
            text(
                """
                SELECT flight_no, full_date,
                       departure_airport_code || ' -> ' || arrival_airport_code AS route,
                       departure_time_24h, arrival_time_24h, duration_minutes
                FROM v_fact_flight_enriched
                ORDER BY full_date, departure_time_24h
                """
            ),
            conn,
        )
    print(preview.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
